version: '3'

tasks:
  celery:app:
    desc: >
      Main application entrypoint.
      Includes celery worker and celery beat.
      Minimal sufficient for app working.
    cmds:
      - celery
        -A peasant.celery worker
        --concurrency=${CELERY_CONCURRENCY}
        -B
        --loglevel ${CELERY_LOGLEVEL} {{.CLI_ARGS}}
    env:
      CELERY_LOGLEVEL: INFO
      CELERY_CONCURRENCY: "1"

  celery:monitoring:
    desc: Monitoring system to celery
    cmds:
      - celery -A peasant.celery flower
  
  test:pytest:
    desc: Run unit tests
    cmds:
      - pytest

  test:mypy:
    desc: Run static typing checks
    cmds:
      - mypy peasant

  test:
    desc: Run all tests
    cmds:
      - task: test:mypy
      - task: test:pytest

  
