version: '3'

tasks:
  build:
    cmds:
      - docker build --tag darkwind8/peasant:v0.0.0 .

  push:
    cmds:
      - docker push darkwind8/peasant:v0.0.0

  run:
    cmds:
      - docker run -it -p 9000:8080 darkwind8/peasant:v0.0.0

  test:
    cmds:
      - curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
